using Entities.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Repositories.EFCore.Config
{
    public class ClinicConfig : IEntityTypeConfiguration<Clinic>
    {
        public void Configure(EntityTypeBuilder<Clinic> builder)
        {
            builder.HasOne(c => c.District)
                .WithMany(d => d.Clinics)
                .HasForeignKey(c => c.DistrictId)
                .OnDelete(DeleteBehavior.Restrict);  // İlçeyi silerken klinikler kalmalı

            builder.HasMany(c => c.ClinicHospitals)
                .WithOne(ch => ch.Clinic)
                .HasForeignKey(ch => ch.ClinicId)
                .OnDelete(DeleteBehavior.Restrict);

            builder.HasData(
    new Clinic { Id = 1, Name = "Kardiyoloji", DistrictId = 1 },
    new Clinic { Id = 2, Name = "Dahiliye", DistrictId = 1 },
    new Clinic { Id = 3, Name = "Ortopedi", DistrictId = 1 },
    new Clinic { Id = 4, Name = "Pediatri", DistrictId = 1 },
    new Clinic { Id = 5, Name = "Dermatoloji", DistrictId = 1 },
    new Clinic { Id = 6, Name = "Göz", DistrictId = 1 },
    new Clinic { Id = 7, Name = "KBB", DistrictId = 1 },
    new Clinic { Id = 8, Name = "Üroloji", DistrictId = 1 },
    new Clinic { Id = 9, Name = "Kadın Doğum", DistrictId = 1 },
    new Clinic { Id = 10, Name = "Nöroloji", DistrictId = 1 },
    new Clinic { Id = 11, Name = "Kardiyoloji", DistrictId = 2 },
    new Clinic { Id = 12, Name = "Dahiliye", DistrictId = 2 },
    new Clinic { Id = 13, Name = "Ortopedi", DistrictId = 2 },
    new Clinic { Id = 14, Name = "Pediatri", DistrictId = 2 },
    new Clinic { Id = 15, Name = "Dermatoloji", DistrictId = 2 },
    new Clinic { Id = 16, Name = "Göz", DistrictId = 2 },
    new Clinic { Id = 17, Name = "KBB", DistrictId = 2 },
    new Clinic { Id = 18, Name = "Üroloji", DistrictId = 2 },
    new Clinic { Id = 19, Name = "Kadın Doğum", DistrictId = 2 },
    new Clinic { Id = 20, Name = "Nöroloji", DistrictId = 2 },
    new Clinic { Id = 21, Name = "Kardiyoloji", DistrictId = 3 },
    new Clinic { Id = 22, Name = "Dahiliye", DistrictId = 3 },
    new Clinic { Id = 23, Name = "Ortopedi", DistrictId = 3 },
    new Clinic { Id = 24, Name = "Pediatri", DistrictId = 3 },
    new Clinic { Id = 25, Name = "Dermatoloji", DistrictId = 3 },
    new Clinic { Id = 26, Name = "Göz", DistrictId = 3 },
    new Clinic { Id = 27, Name = "KBB", DistrictId = 3 },
    new Clinic { Id = 28, Name = "Üroloji", DistrictId = 3 },
    new Clinic { Id = 29, Name = "Kadın Doğum", DistrictId = 3 },
    new Clinic { Id = 30, Name = "Nöroloji", DistrictId = 3 },
    new Clinic { Id = 31, Name = "Kardiyoloji", DistrictId = 4 },
    new Clinic { Id = 32, Name = "Dahiliye", DistrictId = 4 },
    new Clinic { Id = 33, Name = "Ortopedi", DistrictId = 4 },
    new Clinic { Id = 34, Name = "Pediatri", DistrictId = 4 },
    new Clinic { Id = 35, Name = "Dermatoloji", DistrictId = 4 },
    new Clinic { Id = 36, Name = "Göz", DistrictId = 4 },
    new Clinic { Id = 37, Name = "KBB", DistrictId = 4 },
    new Clinic { Id = 38, Name = "Üroloji", DistrictId = 4 },
    new Clinic { Id = 39, Name = "Kadın Doğum", DistrictId = 4 },
    new Clinic { Id = 40, Name = "Nöroloji", DistrictId = 4 },
    new Clinic { Id = 41, Name = "Kardiyoloji", DistrictId = 5 },
    new Clinic { Id = 42, Name = "Dahiliye", DistrictId = 5 },
    new Clinic { Id = 43, Name = "Ortopedi", DistrictId = 5 },
    new Clinic { Id = 44, Name = "Pediatri", DistrictId = 5 },
    new Clinic { Id = 45, Name = "Dermatoloji", DistrictId = 5 },
    new Clinic { Id = 46, Name = "Göz", DistrictId = 5 },
    new Clinic { Id = 47, Name = "KBB", DistrictId = 5 },
    new Clinic { Id = 48, Name = "Üroloji", DistrictId = 5 },
    new Clinic { Id = 49, Name = "Kadın Doğum", DistrictId = 5 },
    new Clinic { Id = 50, Name = "Nöroloji", DistrictId = 5 },
    new Clinic { Id = 51, Name = "Kardiyoloji", DistrictId = 6 },
    new Clinic { Id = 52, Name = "Dahiliye", DistrictId = 6 },
    new Clinic { Id = 53, Name = "Ortopedi", DistrictId = 6 },
    new Clinic { Id = 54, Name = "Pediatri", DistrictId = 6 },
    new Clinic { Id = 55, Name = "Dermatoloji", DistrictId = 6 },
    new Clinic { Id = 56, Name = "Göz", DistrictId = 6 },
    new Clinic { Id = 57, Name = "KBB", DistrictId = 6 },
    new Clinic { Id = 58, Name = "Üroloji", DistrictId = 6 },
    new Clinic { Id = 59, Name = "Kadın Doğum", DistrictId = 6 },
    new Clinic { Id = 60, Name = "Nöroloji", DistrictId = 6 },
    new Clinic { Id = 61, Name = "Kardiyoloji", DistrictId = 7 },
    new Clinic { Id = 62, Name = "Dahiliye", DistrictId = 7 },
    new Clinic { Id = 63, Name = "Ortopedi", DistrictId = 7 },
    new Clinic { Id = 64, Name = "Pediatri", DistrictId = 7 },
    new Clinic { Id = 65, Name = "Dermatoloji", DistrictId = 7 },
    new Clinic { Id = 66, Name = "Göz", DistrictId = 7 },
    new Clinic { Id = 67, Name = "KBB", DistrictId = 7 },
    new Clinic { Id = 68, Name = "Üroloji", DistrictId = 7 },
    new Clinic { Id = 69, Name = "Kadın Doğum", DistrictId = 7 },
    new Clinic { Id = 70, Name = "Nöroloji", DistrictId = 7 },
    new Clinic { Id = 71, Name = "Kardiyoloji", DistrictId = 8 },
    new Clinic { Id = 72, Name = "Dahiliye", DistrictId = 8 },
    new Clinic { Id = 73, Name = "Ortopedi", DistrictId = 8 },
    new Clinic { Id = 74, Name = "Pediatri", DistrictId = 8 },
    new Clinic { Id = 75, Name = "Dermatoloji", DistrictId = 8 },
    new Clinic { Id = 76, Name = "Göz", DistrictId = 8 },
    new Clinic { Id = 77, Name = "KBB", DistrictId = 8 },
    new Clinic { Id = 78, Name = "Üroloji", DistrictId = 8 },
    new Clinic { Id = 79, Name = "Kadın Doğum", DistrictId = 8 },
    new Clinic { Id = 80, Name = "Nöroloji", DistrictId = 8 },
    new Clinic { Id = 81, Name = "Kardiyoloji", DistrictId = 9 },
    new Clinic { Id = 82, Name = "Dahiliye", DistrictId = 9 },
    new Clinic { Id = 83, Name = "Ortopedi", DistrictId = 9 },
    new Clinic { Id = 84, Name = "Pediatri", DistrictId = 9 },
    new Clinic { Id = 85, Name = "Dermatoloji", DistrictId = 9 },
    new Clinic { Id = 86, Name = "Göz", DistrictId = 9 },
    new Clinic { Id = 87, Name = "KBB", DistrictId = 9 },
    new Clinic { Id = 88, Name = "Üroloji", DistrictId = 9 },
    new Clinic { Id = 89, Name = "Kadın Doğum", DistrictId = 9 },
    new Clinic { Id = 90, Name = "Nöroloji", DistrictId = 9 },
    new Clinic { Id = 91, Name = "Kardiyoloji", DistrictId = 10 },
    new Clinic { Id = 92, Name = "Dahiliye", DistrictId = 10 },
    new Clinic { Id = 93, Name = "Ortopedi", DistrictId = 10 },
    new Clinic { Id = 94, Name = "Pediatri", DistrictId = 10 },
    new Clinic { Id = 95, Name = "Dermatoloji", DistrictId = 10 },
    new Clinic { Id = 96, Name = "Göz", DistrictId = 10 },
    new Clinic { Id = 97, Name = "KBB", DistrictId = 10 },
    new Clinic { Id = 98, Name = "Üroloji", DistrictId = 10 },
    new Clinic { Id = 99, Name = "Kadın Doğum", DistrictId = 10 },
    new Clinic { Id = 100, Name = "Nöroloji", DistrictId = 10 },
    new Clinic { Id = 101, Name = "Kardiyoloji", DistrictId = 11 },
    new Clinic { Id = 102, Name = "Dahiliye", DistrictId = 11 },
    new Clinic { Id = 103, Name = "Ortopedi", DistrictId = 11 },
    new Clinic { Id = 104, Name = "Pediatri", DistrictId = 11 },
    new Clinic { Id = 105, Name = "Dermatoloji", DistrictId = 11 },
    new Clinic { Id = 106, Name = "Göz", DistrictId = 11 },
    new Clinic { Id = 107, Name = "KBB", DistrictId = 11 },
    new Clinic { Id = 108, Name = "Üroloji", DistrictId = 11 },
    new Clinic { Id = 109, Name = "Kadın Doğum", DistrictId = 11 },
    new Clinic { Id = 110, Name = "Nöroloji", DistrictId = 11 },
    new Clinic { Id = 111, Name = "Kardiyoloji", DistrictId = 12 },
    new Clinic { Id = 112, Name = "Dahiliye", DistrictId = 12 },
    new Clinic { Id = 113, Name = "Ortopedi", DistrictId = 12 },
    new Clinic { Id = 114, Name = "Pediatri", DistrictId = 12 },
    new Clinic { Id = 115, Name = "Dermatoloji", DistrictId = 12 },
    new Clinic { Id = 116, Name = "Göz", DistrictId = 12 },
    new Clinic { Id = 117, Name = "KBB", DistrictId = 12 },
    new Clinic { Id = 118, Name = "Üroloji", DistrictId = 12 },
    new Clinic { Id = 119, Name = "Kadın Doğum", DistrictId = 12 },
    new Clinic { Id = 120, Name = "Nöroloji", DistrictId = 12 },
    new Clinic { Id = 121, Name = "Kardiyoloji", DistrictId = 13 },
    new Clinic { Id = 122, Name = "Dahiliye", DistrictId = 13 },
    new Clinic { Id = 123, Name = "Ortopedi", DistrictId = 13 },
    new Clinic { Id = 124, Name = "Pediatri", DistrictId = 13 },
    new Clinic { Id = 125, Name = "Dermatoloji", DistrictId = 13 },
    new Clinic { Id = 126, Name = "Göz", DistrictId = 13 },
    new Clinic { Id = 127, Name = "KBB", DistrictId = 13 },
    new Clinic { Id = 128, Name = "Üroloji", DistrictId = 13 },
    new Clinic { Id = 129, Name = "Kadın Doğum", DistrictId = 13 },
    new Clinic { Id = 130, Name = "Nöroloji", DistrictId = 13 },
    new Clinic { Id = 131, Name = "Kardiyoloji", DistrictId = 14 },
    new Clinic { Id = 132, Name = "Dahiliye", DistrictId = 14 },
    new Clinic { Id = 133, Name = "Ortopedi", DistrictId = 14 },
    new Clinic { Id = 134, Name = "Pediatri", DistrictId = 14 },
    new Clinic { Id = 135, Name = "Dermatoloji", DistrictId = 14 },
    new Clinic { Id = 136, Name = "Göz", DistrictId = 14 },
    new Clinic { Id = 137, Name = "KBB", DistrictId = 14 },
    new Clinic { Id = 138, Name = "Üroloji", DistrictId = 14 },
    new Clinic { Id = 139, Name = "Kadın Doğum", DistrictId = 14 },
    new Clinic { Id = 140, Name = "Nöroloji", DistrictId = 14 },
    new Clinic { Id = 141, Name = "Kardiyoloji", DistrictId = 15 },
    new Clinic { Id = 142, Name = "Dahiliye", DistrictId = 15 },
    new Clinic { Id = 143, Name = "Ortopedi", DistrictId = 15 },
    new Clinic { Id = 144, Name = "Pediatri", DistrictId = 15 },
    new Clinic { Id = 145, Name = "Dermatoloji", DistrictId = 15 },
    new Clinic { Id = 146, Name = "Göz", DistrictId = 15 },
    new Clinic { Id = 147, Name = "KBB", DistrictId = 15 },
    new Clinic { Id = 148, Name = "Üroloji", DistrictId = 15 },
    new Clinic { Id = 149, Name = "Kadın Doğum", DistrictId = 15 },
    new Clinic { Id = 150, Name = "Nöroloji", DistrictId = 15 },
    new Clinic { Id = 151, Name = "Kardiyoloji", DistrictId = 16 },
    new Clinic { Id = 152, Name = "Dahiliye", DistrictId = 16 },
    new Clinic { Id = 153, Name = "Ortopedi", DistrictId = 16 },
    new Clinic { Id = 154, Name = "Pediatri", DistrictId = 16 },
    new Clinic { Id = 155, Name = "Dermatoloji", DistrictId = 16 },
    new Clinic { Id = 156, Name = "Göz", DistrictId = 16 },
    new Clinic { Id = 157, Name = "KBB", DistrictId = 16 },
    new Clinic { Id = 158, Name = "Üroloji", DistrictId = 16 },
    new Clinic { Id = 159, Name = "Kadın Doğum", DistrictId = 16 },
    new Clinic { Id = 160, Name = "Nöroloji", DistrictId = 16 },
    new Clinic { Id = 161, Name = "Kardiyoloji", DistrictId = 17 },
    new Clinic { Id = 162, Name = "Dahiliye", DistrictId = 17 },
    new Clinic { Id = 163, Name = "Ortopedi", DistrictId = 17 },
    new Clinic { Id = 164, Name = "Pediatri", DistrictId = 17 },
    new Clinic { Id = 165, Name = "Dermatoloji", DistrictId = 17 },
    new Clinic { Id = 166, Name = "Göz", DistrictId = 17 },
    new Clinic { Id = 167, Name = "KBB", DistrictId = 17 },
    new Clinic { Id = 168, Name = "Üroloji", DistrictId = 17 },
    new Clinic { Id = 169, Name = "Kadın Doğum", DistrictId = 17 },
    new Clinic { Id = 170, Name = "Nöroloji", DistrictId = 17 },
    new Clinic { Id = 171, Name = "Kardiyoloji", DistrictId = 18 },
    new Clinic { Id = 172, Name = "Dahiliye", DistrictId = 18 },
    new Clinic { Id = 173, Name = "Ortopedi", DistrictId = 18 },
    new Clinic { Id = 174, Name = "Pediatri", DistrictId = 18 },
    new Clinic { Id = 175, Name = "Dermatoloji", DistrictId = 18 },
    new Clinic { Id = 176, Name = "Göz", DistrictId = 18 },
    new Clinic { Id = 177, Name = "KBB", DistrictId = 18 },
    new Clinic { Id = 178, Name = "Üroloji", DistrictId = 18 },
    new Clinic { Id = 179, Name = "Kadın Doğum", DistrictId = 18 },
    new Clinic { Id = 180, Name = "Nöroloji", DistrictId = 18 },
    new Clinic { Id = 181, Name = "Kardiyoloji", DistrictId = 19 },
    new Clinic { Id = 182, Name = "Dahiliye", DistrictId = 19 },
    new Clinic { Id = 183, Name = "Ortopedi", DistrictId = 19 },
    new Clinic { Id = 184, Name = "Pediatri", DistrictId = 19 },
    new Clinic { Id = 185, Name = "Dermatoloji", DistrictId = 19 },
    new Clinic { Id = 186, Name = "Göz", DistrictId = 19 },
    new Clinic { Id = 187, Name = "KBB", DistrictId = 19 },
    new Clinic { Id = 188, Name = "Üroloji", DistrictId = 19 },
    new Clinic { Id = 189, Name = "Kadın Doğum", DistrictId = 19 },
    new Clinic { Id = 190, Name = "Nöroloji", DistrictId = 19 },
    new Clinic { Id = 191, Name = "Kardiyoloji", DistrictId = 20 },
    new Clinic { Id = 192, Name = "Dahiliye", DistrictId = 20 },
    new Clinic { Id = 193, Name = "Ortopedi", DistrictId = 20 },
    new Clinic { Id = 194, Name = "Pediatri", DistrictId = 20 },
    new Clinic { Id = 195, Name = "Dermatoloji", DistrictId = 20 },
    new Clinic { Id = 196, Name = "Göz", DistrictId = 20 },
    new Clinic { Id = 197, Name = "KBB", DistrictId = 20 },
    new Clinic { Id = 198, Name = "Üroloji", DistrictId = 20 },
    new Clinic { Id = 199, Name = "Kadın Doğum", DistrictId = 20 },
    new Clinic { Id = 200, Name = "Nöroloji", DistrictId = 20 },
    new Clinic { Id = 201, Name = "Kardiyoloji", DistrictId = 21 },
    new Clinic { Id = 202, Name = "Dahiliye", DistrictId = 21 },
    new Clinic { Id = 203, Name = "Ortopedi", DistrictId = 21 },
    new Clinic { Id = 204, Name = "Pediatri", DistrictId = 21 },
    new Clinic { Id = 205, Name = "Dermatoloji", DistrictId = 21 },
    new Clinic { Id = 206, Name = "Göz", DistrictId = 21 },
    new Clinic { Id = 207, Name = "KBB", DistrictId = 21 },
    new Clinic { Id = 208, Name = "Üroloji", DistrictId = 21 },
    new Clinic { Id = 209, Name = "Kadın Doğum", DistrictId = 21 },
    new Clinic { Id = 210, Name = "Nöroloji", DistrictId = 21 },
    new Clinic { Id = 211, Name = "Kardiyoloji", DistrictId = 22 },
    new Clinic { Id = 212, Name = "Dahiliye", DistrictId = 22 },
    new Clinic { Id = 213, Name = "Ortopedi", DistrictId = 22 },
    new Clinic { Id = 214, Name = "Pediatri", DistrictId = 22 },
    new Clinic { Id = 215, Name = "Dermatoloji", DistrictId = 22 },
    new Clinic { Id = 216, Name = "Göz", DistrictId = 22 },
    new Clinic { Id = 217, Name = "KBB", DistrictId = 22 },
    new Clinic { Id = 218, Name = "Üroloji", DistrictId = 22 },
    new Clinic { Id = 219, Name = "Kadın Doğum", DistrictId = 22 },
    new Clinic { Id = 220, Name = "Nöroloji", DistrictId = 22 },
    new Clinic { Id = 221, Name = "Kardiyoloji", DistrictId = 23 },
    new Clinic { Id = 222, Name = "Dahiliye", DistrictId = 23 },
    new Clinic { Id = 223, Name = "Ortopedi", DistrictId = 23 },
    new Clinic { Id = 224, Name = "Pediatri", DistrictId = 23 },
    new Clinic { Id = 225, Name = "Dermatoloji", DistrictId = 23 },
    new Clinic { Id = 226, Name = "Göz", DistrictId = 23 },
    new Clinic { Id = 227, Name = "KBB", DistrictId = 23 },
    new Clinic { Id = 228, Name = "Üroloji", DistrictId = 23 },
    new Clinic { Id = 229, Name = "Kadın Doğum", DistrictId = 23 },
    new Clinic { Id = 230, Name = "Nöroloji", DistrictId = 23 },
    new Clinic { Id = 231, Name = "Kardiyoloji", DistrictId = 24 },
    new Clinic { Id = 232, Name = "Dahiliye", DistrictId = 24 },
    new Clinic { Id = 233, Name = "Ortopedi", DistrictId = 24 },
    new Clinic { Id = 234, Name = "Pediatri", DistrictId = 24 },
    new Clinic { Id = 235, Name = "Dermatoloji", DistrictId = 24 },
    new Clinic { Id = 236, Name = "Göz", DistrictId = 24 },
    new Clinic { Id = 237, Name = "KBB", DistrictId = 24 },
    new Clinic { Id = 238, Name = "Üroloji", DistrictId = 24 },
    new Clinic { Id = 239, Name = "Kadın Doğum", DistrictId = 24 },
    new Clinic { Id = 240, Name = "Nöroloji", DistrictId = 24 },
    new Clinic { Id = 241, Name = "Kardiyoloji", DistrictId = 25 },
    new Clinic { Id = 242, Name = "Dahiliye", DistrictId = 25 },
    new Clinic { Id = 243, Name = "Ortopedi", DistrictId = 25 },
    new Clinic { Id = 244, Name = "Pediatri", DistrictId = 25 },
    new Clinic { Id = 245, Name = "Dermatoloji", DistrictId = 25 },
    new Clinic { Id = 246, Name = "Göz", DistrictId = 25 },
    new Clinic { Id = 247, Name = "KBB", DistrictId = 25 },
    new Clinic { Id = 248, Name = "Üroloji", DistrictId = 25 },
    new Clinic { Id = 249, Name = "Kadın Doğum", DistrictId = 25 },
    new Clinic { Id = 250, Name = "Nöroloji", DistrictId = 25 },
    new Clinic { Id = 251, Name = "Kardiyoloji", DistrictId = 26 },
    new Clinic { Id = 252, Name = "Dahiliye", DistrictId = 26 },
    new Clinic { Id = 253, Name = "Ortopedi", DistrictId = 26 },
    new Clinic { Id = 254, Name = "Pediatri", DistrictId = 26 },
    new Clinic { Id = 255, Name = "Dermatoloji", DistrictId = 26 },
    new Clinic { Id = 256, Name = "Göz", DistrictId = 26 },
    new Clinic { Id = 257, Name = "KBB", DistrictId = 26 },
    new Clinic { Id = 258, Name = "Üroloji", DistrictId = 26 },
    new Clinic { Id = 259, Name = "Kadın Doğum", DistrictId = 26 },
    new Clinic { Id = 260, Name = "Nöroloji", DistrictId = 26 },
    new Clinic { Id = 261, Name = "Kardiyoloji", DistrictId = 27 },
    new Clinic { Id = 262, Name = "Dahiliye", DistrictId = 27 },
    new Clinic { Id = 263, Name = "Ortopedi", DistrictId = 27 },
    new Clinic { Id = 264, Name = "Pediatri", DistrictId = 27 },
    new Clinic { Id = 265, Name = "Dermatoloji", DistrictId = 27 },
    new Clinic { Id = 266, Name = "Göz", DistrictId = 27 },
    new Clinic { Id = 267, Name = "KBB", DistrictId = 27 },
    new Clinic { Id = 268, Name = "Üroloji", DistrictId = 27 },
    new Clinic { Id = 269, Name = "Kadın Doğum", DistrictId = 27 },
    new Clinic { Id = 270, Name = "Nöroloji", DistrictId = 27 },
    new Clinic { Id = 271, Name = "Kardiyoloji", DistrictId = 28 },
    new Clinic { Id = 272, Name = "Dahiliye", DistrictId = 28 },
    new Clinic { Id = 273, Name = "Ortopedi", DistrictId = 28 },
    new Clinic { Id = 274, Name = "Pediatri", DistrictId = 28 },
    new Clinic { Id = 275, Name = "Dermatoloji", DistrictId = 28 },
    new Clinic { Id = 276, Name = "Göz", DistrictId = 28 },
    new Clinic { Id = 277, Name = "KBB", DistrictId = 28 },
    new Clinic { Id = 278, Name = "Üroloji", DistrictId = 28 },
    new Clinic { Id = 279, Name = "Kadın Doğum", DistrictId = 28 },
    new Clinic { Id = 280, Name = "Nöroloji", DistrictId = 28 },
    new Clinic { Id = 281, Name = "Kardiyoloji", DistrictId = 29 },
    new Clinic { Id = 282, Name = "Dahiliye", DistrictId = 29 },
    new Clinic { Id = 283, Name = "Ortopedi", DistrictId = 29 },
    new Clinic { Id = 284, Name = "Pediatri", DistrictId = 29 },
    new Clinic { Id = 285, Name = "Dermatoloji", DistrictId = 29 },
    new Clinic { Id = 286, Name = "Göz", DistrictId = 29 },
    new Clinic { Id = 287, Name = "KBB", DistrictId = 29 },
    new Clinic { Id = 288, Name = "Üroloji", DistrictId = 29 },
    new Clinic { Id = 289, Name = "Kadın Doğum", DistrictId = 29 },
    new Clinic { Id = 290, Name = "Nöroloji", DistrictId = 29 },
    new Clinic { Id = 291, Name = "Kardiyoloji", DistrictId = 30 },
    new Clinic { Id = 292, Name = "Dahiliye", DistrictId = 30 },
    new Clinic { Id = 293, Name = "Ortopedi", DistrictId = 30 },
    new Clinic { Id = 294, Name = "Pediatri", DistrictId = 30 },
    new Clinic { Id = 295, Name = "Dermatoloji", DistrictId = 30 },
    new Clinic { Id = 296, Name = "Göz", DistrictId = 30 },
    new Clinic { Id = 297, Name = "KBB", DistrictId = 30 },
    new Clinic { Id = 298, Name = "Üroloji", DistrictId = 30 },
    new Clinic { Id = 299, Name = "Kadın Doğum", DistrictId = 30 },
    new Clinic { Id = 300, Name = "Nöroloji", DistrictId = 30 },
    new Clinic { Id = 301, Name = "Kardiyoloji", DistrictId = 31 },
    new Clinic { Id = 302, Name = "Dahiliye", DistrictId = 31 },
    new Clinic { Id = 303, Name = "Ortopedi", DistrictId = 31 },
    new Clinic { Id = 304, Name = "Pediatri", DistrictId = 31 },
    new Clinic { Id = 305, Name = "Dermatoloji", DistrictId = 31 },
    new Clinic { Id = 306, Name = "Göz", DistrictId = 31 },
    new Clinic { Id = 307, Name = "KBB", DistrictId = 31 },
    new Clinic { Id = 308, Name = "Üroloji", DistrictId = 31 },
    new Clinic { Id = 309, Name = "Kadın Doğum", DistrictId = 31 },
    new Clinic { Id = 310, Name = "Nöroloji", DistrictId = 31 },
    new Clinic { Id = 311, Name = "Kardiyoloji", DistrictId = 32 },
    new Clinic { Id = 312, Name = "Dahiliye", DistrictId = 32 },
    new Clinic { Id = 313, Name = "Ortopedi", DistrictId = 32 },
    new Clinic { Id = 314, Name = "Pediatri", DistrictId = 32 },
    new Clinic { Id = 315, Name = "Dermatoloji", DistrictId = 32 },
    new Clinic { Id = 316, Name = "Göz", DistrictId = 32 },
    new Clinic { Id = 317, Name = "KBB", DistrictId = 32 },
    new Clinic { Id = 318, Name = "Üroloji", DistrictId = 32 },
    new Clinic { Id = 319, Name = "Kadın Doğum", DistrictId = 32 },
    new Clinic { Id = 320, Name = "Nöroloji", DistrictId = 32 },
    new Clinic { Id = 321, Name = "Kardiyoloji", DistrictId = 33 },
    new Clinic { Id = 322, Name = "Dahiliye", DistrictId = 33 },
    new Clinic { Id = 323, Name = "Ortopedi", DistrictId = 33 },
    new Clinic { Id = 324, Name = "Pediatri", DistrictId = 33 },
    new Clinic { Id = 325, Name = "Dermatoloji", DistrictId = 33 },
    new Clinic { Id = 326, Name = "Göz", DistrictId = 33 },
    new Clinic { Id = 327, Name = "KBB", DistrictId = 33 },
    new Clinic { Id = 328, Name = "Üroloji", DistrictId = 33 },
    new Clinic { Id = 329, Name = "Kadın Doğum", DistrictId = 33 },
    new Clinic { Id = 330, Name = "Nöroloji", DistrictId = 33 },
    new Clinic { Id = 331, Name = "Kardiyoloji", DistrictId = 34 },
    new Clinic { Id = 332, Name = "Dahiliye", DistrictId = 34 },
    new Clinic { Id = 333, Name = "Ortopedi", DistrictId = 34 },
    new Clinic { Id = 334, Name = "Pediatri", DistrictId = 34 },
    new Clinic { Id = 335, Name = "Dermatoloji", DistrictId = 34 },
    new Clinic { Id = 336, Name = "Göz", DistrictId = 34 },
    new Clinic { Id = 337, Name = "KBB", DistrictId = 34 },
    new Clinic { Id = 338, Name = "Üroloji", DistrictId = 34 },
    new Clinic { Id = 339, Name = "Kadın Doğum", DistrictId = 34 },
    new Clinic { Id = 340, Name = "Nöroloji", DistrictId = 34 },
    new Clinic { Id = 341, Name = "Kardiyoloji", DistrictId = 35 },
    new Clinic { Id = 342, Name = "Dahiliye", DistrictId = 35 },
    new Clinic { Id = 343, Name = "Ortopedi", DistrictId = 35 },
    new Clinic { Id = 344, Name = "Pediatri", DistrictId = 35 },
    new Clinic { Id = 345, Name = "Dermatoloji", DistrictId = 35 },
    new Clinic { Id = 346, Name = "Göz", DistrictId = 35 },
    new Clinic { Id = 347, Name = "KBB", DistrictId = 35 },
    new Clinic { Id = 348, Name = "Üroloji", DistrictId = 35 },
    new Clinic { Id = 349, Name = "Kadın Doğum", DistrictId = 35 },
    new Clinic { Id = 350, Name = "Nöroloji", DistrictId = 35 },
    new Clinic { Id = 351, Name = "Kardiyoloji", DistrictId = 36 },
    new Clinic { Id = 352, Name = "Dahiliye", DistrictId = 36 },
    new Clinic { Id = 353, Name = "Ortopedi", DistrictId = 36 },
    new Clinic { Id = 354, Name = "Pediatri", DistrictId = 36 },
    new Clinic { Id = 355, Name = "Dermatoloji", DistrictId = 36 },
    new Clinic { Id = 356, Name = "Göz", DistrictId = 36 },
    new Clinic { Id = 357, Name = "KBB", DistrictId = 36 },
    new Clinic { Id = 358, Name = "Üroloji", DistrictId = 36 },
    new Clinic { Id = 359, Name = "Kadın Doğum", DistrictId = 36 },
    new Clinic { Id = 360, Name = "Nöroloji", DistrictId = 36 },
    new Clinic { Id = 361, Name = "Kardiyoloji", DistrictId = 37 },
    new Clinic { Id = 362, Name = "Dahiliye", DistrictId = 37 },
    new Clinic { Id = 363, Name = "Ortopedi", DistrictId = 37 },
    new Clinic { Id = 364, Name = "Pediatri", DistrictId = 37 },
    new Clinic { Id = 365, Name = "Dermatoloji", DistrictId = 37 },
    new Clinic { Id = 366, Name = "Göz", DistrictId = 37 },
    new Clinic { Id = 367, Name = "KBB", DistrictId = 37 },
    new Clinic { Id = 368, Name = "Üroloji", DistrictId = 37 },
    new Clinic { Id = 369, Name = "Kadın Doğum", DistrictId = 37 },
    new Clinic { Id = 370, Name = "Nöroloji", DistrictId = 37 },
    new Clinic { Id = 371, Name = "Kardiyoloji", DistrictId = 38 },
    new Clinic { Id = 372, Name = "Dahiliye", DistrictId = 38 },
    new Clinic { Id = 373, Name = "Ortopedi", DistrictId = 38 },
    new Clinic { Id = 374, Name = "Pediatri", DistrictId = 38 },
    new Clinic { Id = 375, Name = "Dermatoloji", DistrictId = 38 },
    new Clinic { Id = 376, Name = "Göz", DistrictId = 38 },
    new Clinic { Id = 377, Name = "KBB", DistrictId = 38 },
    new Clinic { Id = 378, Name = "Üroloji", DistrictId = 38 },
    new Clinic { Id = 379, Name = "Kadın Doğum", DistrictId = 38 },
    new Clinic { Id = 380, Name = "Nöroloji", DistrictId = 38 },
    new Clinic { Id = 381, Name = "Kardiyoloji", DistrictId = 39 },
    new Clinic { Id = 382, Name = "Dahiliye", DistrictId = 39 },
    new Clinic { Id = 383, Name = "Ortopedi", DistrictId = 39 },
    new Clinic { Id = 384, Name = "Pediatri", DistrictId = 39 },
    new Clinic { Id = 385, Name = "Dermatoloji", DistrictId = 39 },
    new Clinic { Id = 386, Name = "Göz", DistrictId = 39 },
    new Clinic { Id = 387, Name = "KBB", DistrictId = 39 },
    new Clinic { Id = 388, Name = "Üroloji", DistrictId = 39 },
    new Clinic { Id = 389, Name = "Kadın Doğum", DistrictId = 39 },
    new Clinic { Id = 390, Name = "Nöroloji", DistrictId = 39 },
    new Clinic { Id = 391, Name = "Kardiyoloji", DistrictId = 40 },
    new Clinic { Id = 392, Name = "Dahiliye", DistrictId = 40 },
    new Clinic { Id = 393, Name = "Ortopedi", DistrictId = 40 },
    new Clinic { Id = 394, Name = "Pediatri", DistrictId = 40 },
    new Clinic { Id = 395, Name = "Dermatoloji", DistrictId = 40 },
    new Clinic { Id = 396, Name = "Göz", DistrictId = 40 },
    new Clinic { Id = 397, Name = "KBB", DistrictId = 40 },
    new Clinic { Id = 398, Name = "Üroloji", DistrictId = 40 },
    new Clinic { Id = 399, Name = "Kadın Doğum", DistrictId = 40 },
    new Clinic { Id = 400, Name = "Nöroloji", DistrictId = 40 },
    new Clinic { Id = 401, Name = "Kardiyoloji", DistrictId = 41 },
    new Clinic { Id = 402, Name = "Dahiliye", DistrictId = 41 },
    new Clinic { Id = 403, Name = "Ortopedi", DistrictId = 41 },
    new Clinic { Id = 404, Name = "Pediatri", DistrictId = 41 },
    new Clinic { Id = 405, Name = "Dermatoloji", DistrictId = 41 },
    new Clinic { Id = 406, Name = "Göz", DistrictId = 41 },
    new Clinic { Id = 407, Name = "KBB", DistrictId = 41 },
    new Clinic { Id = 408, Name = "Üroloji", DistrictId = 41 },
    new Clinic { Id = 409, Name = "Kadın Doğum", DistrictId = 41 },
    new Clinic { Id = 410, Name = "Nöroloji", DistrictId = 41 },
    new Clinic { Id = 411, Name = "Kardiyoloji", DistrictId = 42 },
    new Clinic { Id = 412, Name = "Dahiliye", DistrictId = 42 },
    new Clinic { Id = 413, Name = "Ortopedi", DistrictId = 42 },
    new Clinic { Id = 414, Name = "Pediatri", DistrictId = 42 },
    new Clinic { Id = 415, Name = "Dermatoloji", DistrictId = 42 },
    new Clinic { Id = 416, Name = "Göz", DistrictId = 42 },
    new Clinic { Id = 417, Name = "KBB", DistrictId = 42 },
    new Clinic { Id = 418, Name = "Üroloji", DistrictId = 42 },
    new Clinic { Id = 419, Name = "Kadın Doğum", DistrictId = 42 },
    new Clinic { Id = 420, Name = "Nöroloji", DistrictId = 42 },
    new Clinic { Id = 421, Name = "Kardiyoloji", DistrictId = 43 },
    new Clinic { Id = 422, Name = "Dahiliye", DistrictId = 43 },
    new Clinic { Id = 423, Name = "Ortopedi", DistrictId = 43 },
    new Clinic { Id = 424, Name = "Pediatri", DistrictId = 43 },
    new Clinic { Id = 425, Name = "Dermatoloji", DistrictId = 43 },
    new Clinic { Id = 426, Name = "Göz", DistrictId = 43 },
    new Clinic { Id = 427, Name = "KBB", DistrictId = 43 },
    new Clinic { Id = 428, Name = "Üroloji", DistrictId = 43 },
    new Clinic { Id = 429, Name = "Kadın Doğum", DistrictId = 43 },
    new Clinic { Id = 430, Name = "Nöroloji", DistrictId = 43 },
    new Clinic { Id = 431, Name = "Kardiyoloji", DistrictId = 44 },
    new Clinic { Id = 432, Name = "Dahiliye", DistrictId = 44 },
    new Clinic { Id = 433, Name = "Ortopedi", DistrictId = 44 },
    new Clinic { Id = 434, Name = "Pediatri", DistrictId = 44 },
    new Clinic { Id = 435, Name = "Dermatoloji", DistrictId = 44 },
    new Clinic { Id = 436, Name = "Göz", DistrictId = 44 },
    new Clinic { Id = 437, Name = "KBB", DistrictId = 44 },
    new Clinic { Id = 438, Name = "Üroloji", DistrictId = 44 },
    new Clinic { Id = 439, Name = "Kadın Doğum", DistrictId = 44 },
    new Clinic { Id = 440, Name = "Nöroloji", DistrictId = 44 },
    new Clinic { Id = 441, Name = "Kardiyoloji", DistrictId = 45 },
    new Clinic { Id = 442, Name = "Dahiliye", DistrictId = 45 },
    new Clinic { Id = 443, Name = "Ortopedi", DistrictId = 45 },
    new Clinic { Id = 444, Name = "Pediatri", DistrictId = 45 },
    new Clinic { Id = 445, Name = "Dermatoloji", DistrictId = 45 },
    new Clinic { Id = 446, Name = "Göz", DistrictId = 45 },
    new Clinic { Id = 447, Name = "KBB", DistrictId = 45 },
    new Clinic { Id = 448, Name = "Üroloji", DistrictId = 45 },
    new Clinic { Id = 449, Name = "Kadın Doğum", DistrictId = 45 },
    new Clinic { Id = 450, Name = "Nöroloji", DistrictId = 45 },
    new Clinic { Id = 451, Name = "Kardiyoloji", DistrictId = 46 },
    new Clinic { Id = 452, Name = "Dahiliye", DistrictId = 46 },
    new Clinic { Id = 453, Name = "Ortopedi", DistrictId = 46 },
    new Clinic { Id = 454, Name = "Pediatri", DistrictId = 46 },
    new Clinic { Id = 455, Name = "Dermatoloji", DistrictId = 46 },
    new Clinic { Id = 456, Name = "Göz", DistrictId = 46 },
    new Clinic { Id = 457, Name = "KBB", DistrictId = 46 },
    new Clinic { Id = 458, Name = "Üroloji", DistrictId = 46 },
    new Clinic { Id = 459, Name = "Kadın Doğum", DistrictId = 46 },
    new Clinic { Id = 460, Name = "Nöroloji", DistrictId = 46 },
    new Clinic { Id = 461, Name = "Kardiyoloji", DistrictId = 47 },
    new Clinic { Id = 462, Name = "Dahiliye", DistrictId = 47 },
    new Clinic { Id = 463, Name = "Ortopedi", DistrictId = 47 },
    new Clinic { Id = 464, Name = "Pediatri", DistrictId = 47 },
    new Clinic { Id = 465, Name = "Dermatoloji", DistrictId = 47 },
    new Clinic { Id = 466, Name = "Göz", DistrictId = 47 },
    new Clinic { Id = 467, Name = "KBB", DistrictId = 47 },
    new Clinic { Id = 468, Name = "Üroloji", DistrictId = 47 },
    new Clinic { Id = 469, Name = "Kadın Doğum", DistrictId = 47 },
    new Clinic { Id = 470, Name = "Nöroloji", DistrictId = 47 },
    new Clinic { Id = 471, Name = "Kardiyoloji", DistrictId = 48 },
    new Clinic { Id = 472, Name = "Dahiliye", DistrictId = 48 },
    new Clinic { Id = 473, Name = "Ortopedi", DistrictId = 48 },
    new Clinic { Id = 474, Name = "Pediatri", DistrictId = 48 },
    new Clinic { Id = 475, Name = "Dermatoloji", DistrictId = 48 },
    new Clinic { Id = 476, Name = "Göz", DistrictId = 48 },
    new Clinic { Id = 477, Name = "KBB", DistrictId = 48 },
    new Clinic { Id = 478, Name = "Üroloji", DistrictId = 48 },
    new Clinic { Id = 479, Name = "Kadın Doğum", DistrictId = 48 },
    new Clinic { Id = 480, Name = "Nöroloji", DistrictId = 48 },
    new Clinic { Id = 481, Name = "Kardiyoloji", DistrictId = 49 },
    new Clinic { Id = 482, Name = "Dahiliye", DistrictId = 49 },
    new Clinic { Id = 483, Name = "Ortopedi", DistrictId = 49 },
    new Clinic { Id = 484, Name = "Pediatri", DistrictId = 49 },
    new Clinic { Id = 485, Name = "Dermatoloji", DistrictId = 49 },
    new Clinic { Id = 486, Name = "Göz", DistrictId = 49 },
    new Clinic { Id = 487, Name = "KBB", DistrictId = 49 },
    new Clinic { Id = 488, Name = "Üroloji", DistrictId = 49 },
    new Clinic { Id = 489, Name = "Kadın Doğum", DistrictId = 49 },
    new Clinic { Id = 490, Name = "Nöroloji", DistrictId = 49 },
    new Clinic { Id = 491, Name = "Kardiyoloji", DistrictId = 50 },
    new Clinic { Id = 492, Name = "Dahiliye", DistrictId = 50 },
    new Clinic { Id = 493, Name = "Ortopedi", DistrictId = 50 },
    new Clinic { Id = 494, Name = "Pediatri", DistrictId = 50 },
    new Clinic { Id = 495, Name = "Dermatoloji", DistrictId = 50 },
    new Clinic { Id = 496, Name = "Göz", DistrictId = 50 },
    new Clinic { Id = 497, Name = "KBB", DistrictId = 50 },
    new Clinic { Id = 498, Name = "Üroloji", DistrictId = 50 },
    new Clinic { Id = 499, Name = "Kadın Doğum", DistrictId = 50 },
    new Clinic { Id = 500, Name = "Nöroloji", DistrictId = 50 }
);
        }
    }
}